spring.application.name=Genderize
server.port=8000

# ===============================
# DATABASE (Railway)
# ===============================
spring.datasource.url=jdbc:postgresql://tramway.proxy.rlwy.net:52865/railway
spring.datasource.username=postgres
spring.datasource.password=ocmXwikaVaPlUdSLzdakcgwSshSYYQMC
spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# JACKSON (ISO 8601 UTC)
# ===============================
spring.jackson.time-zone=UTC
spring.jackson.serialization.write-dates-as-timestamps=false

# ===============================
# LOGGING
# ===============================
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=ERROR
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.engine.jdbc.spi.SqlExceptionHelper=ERROR
logging.level.org.hibernate.type.descriptor.sql=OFF
logging.level.com.app=TRACE



# ===============================
# PROFILE
# ===============================
genderize-base-url=https://api.genderize.io?name=%s
agify-base-url=https://api.agify.io?name=%s
nationalize-base-url=https://api.nationalize.io?name=%s
# ===============================
# GITHUB
# ===============================
github-base-url=https://github.com/login/oauth/
github-client-id=Ov23liLQ6hez1rqua0VQ
github-client-secret=71498ca1922a047a94711b48236cb54e585e4949
github-token-url=${github-base-url}access_token
github-user-url=https://api.github.com/user
github-authorize-url=${github-base-url}authorize

# ===============================
# JWT
# ===============================
jwt-secret=3b6e9f3b77a0d3c67d9e5c8d1e4f7a2c9b5d6c6e2a8d4f1c5b9f0af2e8a4b1c